name: Update README with GitHub Stats

on:
  schedule:
    - cron: '*/2 * * * *' # Atualiza a cada 2 minutos

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        run: |
          STATS=$(curl -s "https://github-readme-stats.vercel.app/api?username=MateusSKV9&theme=radical&show_icons=true&rank_icon=percentile")
          echo "$STATS"

      - name: Update README
        run: |
          # Adiciona as estatísticas ao final do README.md existente
          STATS_URL="![GitHub Stats](https://github-readme-stats.vercel.app/api?username=MateusSKV9&theme=radical&show_icons=true&rank_icon=percentile)"
          echo "$STATS_URL" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git commit -m 'Updated README with GitHub Stats'
          git push
